name: Stable Checkout
description: Checkout repositories into a stable path, without the agent name
author: https://github.com/EmbarkStudios
configuration:
  properties:
    enable:
      type: boolean
