#!/bin/bash
set -e -o pipefail

# Normally this is build_path/agent_name/org_slug/pipeline_slug
export BUILDKITE_BUILD_CHECKOUT_PATH="$BUILDKITE_BUILD_PATH/$BUILDKITE_ORGANIZATION_SLUG/$BUILDKITE_PIPELINE_SLUG"
